### ISSUE TITLE
support cache stars

### ISSUE THREAD

**Issue by tshu-w** [xuchunyang/github-stars.el#3]
fetching stars take a litte time, could you support cache stars like helm-github-stars.

**Comment by xuchunyang** [comment]
The stars is already cached during the Emacs session via the variable `github-stars`. 

You can restore the value when Emacs starts to prepare the cache, e.g., using the builtin library savehist's `savehist-additional-variables` (I assume it supports Hash Table) or use some 3rd party libraries such as https://elpa.gnu.org/packages/persist.html
